### ISSUE TITLE
add DICOM (aka supp 145) support

### ISSUE THREAD

**Issue by malaterre** [openslide/openslide#142]
It would be nice to add initial DICOM support, see initial work at (aka nema vendor):

http://lists.andrew.cmu.edu/pipermail/openslide-users/2014-August/000893.html

**Comment by malaterre** [comment]
For reference: http://lists.andrew.cmu.edu/pipermail/openslide-users/2015-March/001028.html

**Comment by sharmaashish** [comment]
Any plans on bringing in Mathieu's 'quick n dirty' patch into the release cycle?

**Comment by bgilbert** [comment]
I'm swamped at the moment and haven't yet had a chance to look at the patch.  I haven't forgotten about it, though.

**Comment by malaterre** [comment]
ping ?

**Comment by bgilbert** [comment]
Reviewed at #157.  My apologies for the extended delay.

As an experiment, I used [Reviewable](https://reviewable.io/) to do the review; please use [their system](https://reviewable.io/reviews/openslide/openslide/157) for followup discussion.  So far, Reviewable seems better than GitHub's built-in comment system, and I'm thinking about enabling it for the entire repository.  Feedback is welcome.

**Comment by jodogne** [comment]
For reference, the Orthanc project now provides a free and open-source implementation of Supplement 145. This implementation can be configured to use OpenSlide while generating the DICOM images. http://www.orthanc-server.com/static.php?page=wsi

**Comment by fedorov** [comment]
Any updates on this since Nov 2016?

**Comment by jaharkes** [comment]
From the last updates on that pull request #157, it looks like it got stalled both at the reviewing stage (2 of 6 files reviewed) as well as in resolving those issues brought forward during the review (40 unresolved discussions).

When I try to go to the reviewable site to see the actual review, either it no longer exists, or it won't let 
me see the actual review until I give it access to my github account? and I'm not entirely comfortable with that.

**Comment by malaterre** [comment]
Most remarks from @bgilbert are pretty trivial to implement. I only remember one that was not, apparently I used one of the TIFF implementation as template but I should have used something else. So my code may need to be refactor quite a bit (good knowledge of openslide required).

**Comment by hackermd** [comment]
> We should try to use an existing DICOM library if possible, rather than hand-parsing the DICOM container. There appear to be reasonable libraries in C++ ([DCMTK](http://dicom.offis.de/dcmtk.php.en) and [GDCM](http://gdcm.sourceforge.net/wiki/index.php/Main_Page)), but sadly none in C.

@bgilbert we have been developing a C library for reading DICOM files: https://github.com/hackermd/libdicom.
There is still some work to be done on the road to 1.0, but the library could be useful for adding DICOM support to Openslide.

**Comment by sharmaashish** [comment]
We should keep an island this and maybe support it at some point in the future but definitely keep an eye on it

Best,
Ashish

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
From: Markus D. Herrmann ***@***.***>
Sent: Sunday, January 30, 2022 3:49:20 PM
To: openslide/openslide ***@***.***>
Cc: Sharma, Ashish ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [openslide/openslide] add DICOM (aka supp 145) support (#142)


We should try to use an existing DICOM library if possible, rather than hand-parsing the DICOM container. There appear to be reasonable libraries in C++ (DCMTK<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdicom.offis.de%2Fdcmtk.php.en&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Aojhhutz4ZGHponFYMVYRPWgmfpQ56otp%2B%2F%2BuVwAnD4%3D&reserved=0> and GDCM<https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgdcm.sourceforge.net%2Fwiki%2Findex.php%2FMain_Page&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QYiY6TA%2FrblY9zT3QD8hMvc%2BoGL%2B6QTTwVukI9oUsP0%3D&reserved=0>), but sadly none in C.

@bgilbert<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbgilbert&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x6NtISEseMgPfe1wVqL%2Fd2gCIM%2FPF99WNUjucTjP9zI%3D&reserved=0> we have been developing a C library for reading DICOM files: https://github.com/hackermd/libdicom<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhackermd%2Flibdicom&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2WAkj%2FP%2BWGQ%2FnJ8clrMnA8ufAb%2F0wjxlpaQvGur2bek%3D&reserved=0>.
There is still some work to be done on the road to 1.0, but the library could be useful for adding DICOM support to Openslide.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopenslide%2Fopenslide%2Fissues%2F142%23issuecomment-1025227859&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qH6dmudryHJCV4hFeiaaRADQ%2FY3a5E5EMouEdkf2O5g%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACANHTZKJJ7XBG75SK6KIJDUYWP5BANCNFSM4AWVQGHQ&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PeqAb3T4ykztMhU19WREFEs48vWfv%2FzSKyHM24XXVAU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bBWxBNZlrKHgGnXzlEgMKh61T0QB1Wo%2B3GGp8tiEdlU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cashish.sharma%40emory.edu%7C8f6ce5b2ec854d6dc89408d9e431fdb3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637791725642136369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hyTtqPubU23XI36Uso9Fp7X3rwAwnnP55ElocO3VrsQ%3D&reserved=0>.

**Comment by bgilbert** [comment]
#431 has an initial DICOM driver based on libdicom (https://github.com/openslide/openslide/issues/142#issuecomment-1025227859), and there are plans to extend it in future PRs.

**Comment by j0d0nn** [comment]
#446 extends the DICOM vendor code to expose some openslide properties, @bgilbert @jcupitt

**Comment by bgilbert** [comment]
Git `main` now has a reasonably complete DICOM implementation.  There are still DICOM slides that OpenSlide doesn't support (please report these!) but this should be a good starting point.

Thanks @malaterre for the initial implementation, and @hackermd and @jcupitt for the current one!
