### ISSUE TITLE
UTF-16 BOM issues on Windows 32 since September 2015, due to "g_convert", which result in inability to open many slides.

### ISSUE THREAD

**Issue by Markus-PP** [openslide/openslide#176]
Talking about source file src/openslide-util.c:

The new function FILE *do_fopen(const char *path...) does not work correctly on my tested Windows systems. (these were: XP 32, Vista 32, W7 64). I have been using the openslide WIN32 build compiled by  "build.sh" which has glib 2.48.

I checked and observed that g_convert (..:"UTF-16","UTF-8"..) creates a BOM (byte order mark, 0xFEFF) at the beginning of the converted string, and the Windows API apparently can't handle this.

I found two possible solutions:

A) Keep using g_convert and remove a possible BOM before passing the strings to _wfopen(), as such:
```
line 182:
  #define SKIP_BOM(wstr) ( *(uint16_t*)(wstr)==(uint16_t)0xFEFF ? (uint16_t*)(wstr)+1 : (uint16_t*)(wstr) )
  f = _wfopen(SKIP_BOM(path16), SKIP_BOM(mode16));

```
B) Use the glib function g_utf8_to_utf16() instead of g_convert(). The glib internal g_utf8_to_utf16 does not call any external conversion functions and does not seem to produce a BOM.
```
line 169: wchar_t *path16 = g_utf8_to_utf16(path, -1, NULL, NULL, err);
line 175: wchar_t *mode16 = g_utf8_to_utf16(mode, -1, NULL, NULL, err);
```
When I apply change A) or B) I have no more code page compatibility issues on my Windows systems.

**Comment by bgilbert** [comment]
Thank you for tracking this down!  We clearly should have been using `g_utf8_to_utf16()`, but I didn't know it existed.

How this happened:

1. Before glib 2.47.6, `g_convert()` did not add the BOM.
2. On Windows, glib implements `g_convert()` via a bundled copy of [win-iconv](https://github.com/win-iconv/win-iconv).  2.47.6 [includes](http://ftp.gnome.org/pub/gnome/sources/glib/2.47/glib-2.47.6.news) an updated copy of this code.
3. openslide-winbuild inherited the problem when it was updated to glib 2.48.0 in openslide/openslide-winbuild@c8c2b541.  I didn't catch the problem at the time because I tested -winbuild against OpenSlide 3.4.1, not OpenSlide master.
4. Then, when the *entire* test suite started failing in CI, I assumed there was a problem with the test VM, and never got around to debugging it.

The good news is that affected nightly builds failed the automated smoke test and were not uploaded to the website.
