### ISSUE TITLE
Level Downsample Floating Point Error

### ISSUE THREAD

**Issue by Richarizardd** [openslide/openslide#177]
My team and I are using OpenSlide-Python across multiple Ubuntu machines (a mix of versions 1.1.1 and 1.1.0). We noticed that on machines that were first using 1.1.1, the instance method for the OpenSlide object "OpenSlide.level_downsamples" was incorrectly reporting floats, which in turn messes with the instance methods "OpenSlide.level_dimensions" and "OpenSlide.read_region."

Below are two Ubuntu 14.04 desktops with Anaconda installed trying to open up the same whole-slide image. The second desktop first had OpenSlide 1.1.1 installed. We tried to reinstall OpenSlide 1.1.0 on the second desktop, but the issue still persisted.

**Correct**
<img width="1159" alt="screen shot 2016-06-21 at 10 00 40 am" src="https://cloud.githubusercontent.com/assets/10300839/16232932/74674d22-379a-11e6-9c16-2a40dd8d47b2.png">

**Incorrect**
<img width="1020" alt="screen shot 2016-06-21 at 10 00 19 am" src="https://cloud.githubusercontent.com/assets/10300839/16232933/75d05190-379a-11e6-957e-0c3febb2fa2e.png">

**Comment by bgilbert** [comment]
Hi @Richarizardd, the problem is actually the version of OpenSlide (`openslide.__library_version__`) on the two machines: the "correct" machine has OpenSlide 3.4.1 and the "incorrect" machine has an older version.  Upgrading the "incorrect" machine to OpenSlide 3.4.1 should fix the problem.

Background: Downsamples have always been floats, and are calculated from the level dimensions rather than the other way around.  `Tumor_002.tif` is a Philips TIFF.  For some reason, Philips TIFF pads the level dimensions to a multiple of the TIFF tile size, so the dimensions actually recorded in the file are the "incorrect" ones.  Older OpenSlide reads those level dimensions and computes the strange downsamples you're seeing, but OpenSlide 3.4.1 has a Philips TIFF driver that knows how to correct for the extra padding.
