### ISSUE TITLE
openslide.pc file should include at least -lxml2

### ISSUE THREAD

**Issue by mathstuf** [openslide/openslide#185]
## Context

**Issue type**: bug
**Operating system**: Linux
**Platform**: 64bit (but irrelevant here)
**OpenSlide version**: 3.4.1
**Slide format**: any

## Details

The `.pc` file shipped by openslide does not have a `Requires: libxml-2.0` line in it. There may be more missing.

**Comment by bgilbert** [comment]
`Requires: X` means that an application that uses OpenSlide also needs header files from X, or needs to be linked directly with X.  (In other words, OpenSlide requires an application to interact with X's API or ABI.)  None of OpenSlide's dependencies are exposed to applications in this way, so we don't declare any `Requires`.

`Requires.private` is similar, but only applies to static linking.  A statically-linked application really *does* need to link directly with libraries used by other libraries, so declaring `Requires.private` could potentially be useful.  However, there are several downsides (see 8bccd092fc7c242b3a1a71c1ad7ce3c136189ade) and I'm not convinced that anyone should statically link with OpenSlide in the first place.

What problem are you trying to solve?

**Comment by mathstuf** [comment]
We're having problems linking openslide from VTK, but I'm unable to reproduce them again (it appears we were doing shared builds, but the logs have since expired, so I'm not sure what the exact error message was anymore). I'll close the MR for now, but leave this open since static builds are still incomplete.

If openslide isn't really going to support static libraries, could a big warning be output during configure?

**Comment by bgilbert** [comment]
We don't do anything to assist static builds, but we don't impede them either.  Since that's also true of many other open-source libraries, I'm not sure that a configure warning would make sense.  In practice, building OpenSlide statically already requires building all of its dependencies, because static builds of those libraries are not typically packaged.  After doing that work, it should be straightforward for an application author to directly list OpenSlide's dependencies on their linker command line, rather than getting them from pkg-config.

(For the record, there's another caveat to static linking: in order to comply with the LGPLv2.1, the application's distributor must ensure that users can relink the application with a modified version of OpenSlide.  If the application is not open source, this may require distributing the application's object files.)

I'll go ahead and close this.  If you encounter the build problem again, feel free to open another bug or ask on the openslide-users mailing list.

**Comment by mathstuf** [comment]
My worry is that if openslide is under some other lib and a static build is wanted, that other lib needs patched to list all of openslide's dependencies itself rather than having pkg-config Just Work. But yeah, static isn't really that big a deal for me, I just can't remember/reproduce why we were getting missing symbols :) .

**Comment by bgilbert** [comment]
Yeah, I agree that the current situation is not ideal; I just think it's the right functionality/complexity trade-off for a feature with no known or anticipated users and an available workaround.  If someone turns up with an actual need for `Requires.private`, I'm willing to revisit the issue.

(Note for the future: we could work around [fd.o #4738](https://bugs.freedesktop.org/show_bug.cgi?id=4738) by emitting `Requires.private`/`Libs.private` only if `--enable-static`.)
