### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by agoode** [openslide/openslide#195]
https://github.com/openslide/openslide/settings/branches/master

I recommend enabling all the options on this page. This will force integration tests to pass, branches to be up to date, and ensure code review happens (even for administrators). I don't think this will be too strict, but if so, we can weaken the settings.

This will help avoid push mistakes and improve code quality through automated and manual review.

**Comment by bgilbert** [comment]
Once we have immediate automated testing via #193, disabling direct pushes may be a good idea.  I'm not convinced our developer pool is large enough to enforce code review by technical means rather than convention, though.  For example, right now we only have one reviewer (me) and I'd like to be able to get my own code merged.  😉

**Comment by jaharkes** [comment]
LGTM 🙂

**Comment by bgilbert** [comment]
All OpenSlide repos now have branch protection enabled for the `main` branch.  They all require PRs when merging [1], enforce CI checks where CI exists, and enforce those rules against administrators.  For the reasons in https://github.com/openslide/openslide/issues/195#issuecomment-285151527, we currently don't require code review.  We also don't require branches to be up to date because IMO that's an antipattern (unnecessary for slow projects, unworkable for fast ones).  We can always revisit these settings later as needed.

[1] Except for [builds](https://github.com/openslide/builds), to allow GitHub Actions to push automated commits.
