### ISSUE TITLE
Is this project no longer active ? 

### ISSUE THREAD

**Issue by boxerab** [openslide/openslide#217]
No commits in 6 months.

Thanks!

**Comment by bgilbert** [comment]
It's active in my head, at least. 🙂  I haven't had much free time to work on OpenSlide in a while, but I do still plan to get back to it when I can. If, for some reason, that turns out not to happen, I'll at least make sure to tie up loose ends -- e.g. making sure there's a long-term home for the sample slides.

**Comment by boxerab** [comment]
Hi Benjamin,
Thanks for the update, and for all of your hard work on this project. I know maintaining an OSS project over the long haul is very challenging.  How large is the rest of the community? If you stepped away, would the project continue to move forward?  
Cheers,
Aaron

**Comment by Markus-PP** [comment]
Hello Aaron,
This library sure is in use by several projects, and there is considerable activity on the user mailing list. This alone should ensure Openslide is here to stay.
https://lists.andrew.cmu.edu/pipermail/openslide-users/

**Comment by boxerab** [comment]
Thanks, folks. You have answered my origin questions. Its good to know that the project is healthy.
Closing.
