### ISSUE TITLE
Update OpenJPEG version to 2.3

### ISSUE THREAD

**Issue by boxerab** [openslide/openslide#218]
Latest version decode is 3X or more faster than previous versions. Also, large number of bugs
have been fixed.

**Comment by bgilbert** [comment]
If you mean the Windows binaries, this is now done in https://github.com/openslide/openslide-winbuild/commit/b5caeeaa510b73ffa62162181b5cd351ead4a33a and a [nightly build](https://buildbot.openslide.org/snapshots/windows/) is available.  It's been a while since an official release of the Windows binaries; I'll look into making a new one.

**Comment by boxerab** [comment]
Cool. Thanks.

**Comment by bgilbert** [comment]
[Done](http://openslide.org/download/#windows-binaries)!

**Comment by boxerab** [comment]
Kool and the Gang!
