### ISSUE TITLE
how i do get a downsampled region from missing level?

### ISSUE THREAD

**Issue by ade90036** [openslide/openslide#221]
## Context

**Issue type**: in quest of knowledge 
**Operating system**: Mac OS 10.11
**Platform** (x86_64): 
**OpenSlide version**: 3.4.1 
**Slide format**: CMU-1-Small-Region.svs 

## Details
I'm trying to use "openslide_read_region" to request a downsample region from a non-existent level.
I'm using the "CMU-1-Small-Region.svs" which only contains 1 level:

**[native] level 0, dimensions=(2220 x 2967), tileW=240, tileH=240, downsample=1.000000**

But a viewer could request an image from a different magnification (downsampled)?

For example a viewer could be looking at a particular region and then you change magnification you should be able to load the same region in the different magnification.

So, for example, if i'm looking at a region: (x,y,w,h,level)
**(0,0,240,240,0)** == 20X
then i change magnification
**(0,0,240,240,1)** == 10X
But unfortunately, at the moment, this returns an empty buffer.. (black).

I would have expected that openslide_read_region could find that the requested level doesn't exists and then request the same region from the higher magnification:
**(0,0,480,480,0)**
and the using cairo_resize() dynamically downsample the region so that it could fulfill the request: 
**(0,0,240,240,1)** 

Is there another function i could call?

I don't want to implement a custom downsampling algorithm as i feel this should be part of the library and therefore easily achievable within.

could you suggest a possible path through this issue, possibly pointing what is the best approach to implement this in openslide?

Regards

Andrea

**Comment by bgilbert** [comment]
Hi Andrea, OpenSlide is intended as a low-level library to abstract away the details of the various formats it supports.  Higher-level operations such as downsampling, rotation, color correction, etc., are left to the application, or to a higher-level library that uses OpenSlide.  Thus, OpenSlide intentionally provides access only to the pixels that actually exist in the slide file (with some very limited exceptions) and the API provides no way to do what you're trying to do.

For an example of wrapping a downsampling mechanism around OpenSlide, see the [Deep Zoom implementation](https://github.com/openslide/openslide-python/blob/master/openslide/deepzoom.py) in OpenSlide Python.  [libvips](https://jcupitt.github.io/libvips/), a higher-level image-processing library that can read images via OpenSlide, may also be of interest to you.

**Comment by ade90036** [comment]
Hi Ben, 

I get that openslide provide an abstraction level to obtain an uniformal image access, regardless of the format been used, its great.

Yes, color correction i would consider it to be advanced features. 

However don't agree that "downsampling", or requesting an image outside an available level, should be considered an advance operation. In comparison, NDP.Read (Hamamatsu SDK) and Aperio SDK (Before they where acquired from Leica) provided this functionality out of the box with their are low-level SDK, accessing raw image format.

I'm only asking this because i can see that this line is blurry, in technical term, to what has already been implemented.

- openslide provide read_missing_tile, which request an image from the higher magnification when it doesn't have it. (implements _downsampling_)
- openslide already provide a way to request a any size image (even if cairo will not allow surfaces larger than 32767 pixels)
- openslide already provide means to resize image (_cairo_translate_) if you have requests an area with a nevative x,y
- openslide "nearly" has exposed the "make yourself" functionality from _openslide_cairo_read_region_, which it means that you already considered the need to add additional capabilities imaging capabilities to the library. 

I still feel that this should be part of the library as many implementing higher-level libraries or viewer will be ill equipped to perform this task due to performance, speed (in Python case) and complexity.

I have implemented in downsampling function in 10 lines of code in openslide, which would have taken me, ages to implement from a consuming application because i didn't have all the pieces i needed.

```
uint32_t * openslide_read_region_with_downsample(openslide_t *osr,
			   int64_t x, int64_t y,
			   double downsample,
			   int64_t w, int64_t h)
```

Anyway, if you change you mind..

Ade

**Comment by bgilbert** [comment]
Thanks for your feedback, but I don't think this is likely to change.  There are many existing libraries for doing generic image processing, and OpenSlide has nothing unique to contribute in that space.  The points you mentioned are all implementation details, to one degree or another, and thus don't address the conceptual question of what tasks OpenSlide is responsible for.  To address them briefly:

1. `render_missing_tile` is a workaround for broken slide files created by certain versions of the scanner software.  It cannot be implemented outside the library because the caller doesn't have enough information to locate missing tiles.
2. cairo is an implementation detail which is not exposed by OpenSlide's API.  As such, it's our responsibility to work around cairo's limitations (where possible) in cases where OpenSlide's API is more general than cairo's.
3. I agree that that design choice is not the only plausible one that could have been made.  Since `openslide_read_region` is fundamentally about translating a viewport across a slide level, I think it's fairly harmless to allow negative coordinates, and it fits slightly better with OpenSlide's latching error-handling model.  Either way, I don't see that choice being as problematic as synthesizing entire levels.
4. `openslide_cairo_read_region` was never in the exported API, and I now believe it to have been a mistake.  I intend to remove it eventually.

In addition:

5. The Hamamatsu VMS driver, regrettably, does synthesize downsampled levels.  This is necessary because the format assumes that downsampling can be efficiently performed via partial decoding of JPEGs.  The caller doesn't see the compressed JPEG data and thus cannot implement this optimization itself, so OpenSlide must do it.  In mitigation, the synthesized levels are downsampled strictly by powers of 2.

You mentioned that you don't have all the pieces you need to implement downsampling outside OpenSlide.  How so?  OpenSlide Java, OpenSlide Python, VIPS, and many other programs do it successfully.

**Comment by ade90036** [comment]
Ok. Thats fine.

Thanks for your detail explaination.

Ive created a fork for my side project.

Regardd
