### ISSUE TITLE
How is openslide threadsafe?

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#242]
In the documentation it says:

> An openslide_t object can be used concurrently from multiple threads
> without locking. (But you must lock or otherwise use memory barriers
> when passing the object between threads.)

I don't understand the second sentence so much. Can somebody maybe elaborate here a bit?

Our problem is that we experience speed issues when multiple processes access the same openslide object.

Therefore, I have following questions:

1) We create one openslide object for a specific file and put it into the Computer's MemoryCache. Now if multiple processes (e.g. openseadragon queries multiple tiles in different concurrent requests) access this object, is it interenally processing the requests one after the other? Such that in the end, it is basically serving the tiles sequencially, instead of really parallel?

2) Would it be possible (and better) to create multiple openslide instances pointing to the same file? Or is will this trigger a file access violation (e.g. file already in use)?

Does somebody have ideas or experience?

Thank you!

**Comment by jaharkes** [comment]
This isn't really a bug or feature request for openslide, so the github issue tracker probably isn't the best place.

It has been a while since I last looked at this, so my memory may be hazy, but calls into openslide to render a tile are pretty stateless. The only shared resource between threads is a cache for recently read parts from the whole slide image. The part of the code that stitches the requested region together uses this to avoid having to re-read parts that are straddling adjoining tiles.

So if several threads request adjoining or overlapping tiles (common situation for seadragon clients) this cache will both serialize reads of the same part of the whole slide, and allow parallel reads of different parts. And if the cache is larger than the working set it may avoid disk I/O when parts were read previously, i.e. as a user is moving around the image.

Since OpenSlide never writes to the underlying wholeslide images, multiple instances can point to the same file without any access violations. I don't know if the cache I mentioned before is shared between openslide_t handles, or if it is a per-handle cache. If it is shared then multiple handles would probably end up giving you more cache misses.

**Comment by bgilbert** [comment]
Yes, the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/) is the right place for support questions.

The second sentence just means that the `openslide_t *` must not be visible to a thread before the internal OpenSlide data that it refers to.  An easy way to accomplish this is to put your `openslide_t *` into a data structure (such as a cache) which is protected by a lock, because locks provide the correct memory barrier semantics.  If you understand how to use memory barriers correctly, you can use those instead of locking.

OpenSlide tries to be as lock-free as possible, so in general OpenSlide should perform reads in parallel.  (This is true to a fault; see #103.)  Multiple handles pointing to the same file do not share a tile cache; this may be better or worse depending on your application, since the cache cannot be configured by the user (#38).
