### ISSUE TITLE
deepzoom_tile.py 500 Internal Server Error

### ISSUE THREAD

**Issue by ducpm0301** [openslide/openslide#263]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
I have install success but when i run  examples of deepzoom_tile.py (http://localhost/cgi-enabled/openslide-python/examples/deepzoom/deepzoom_tile.py ) have err 500 : Internal Server Error
I check log file, i saw err below :
<img width="1225" alt="screen shot 2019-02-14 at 12 28 12 am" src="https://user-images.githubusercontent.com/4056966/52731074-6e8e0080-2fef-11e9-8a48-267e8c89e4fb.png">
<img width="898" alt="screen shot 2019-02-14 at 12 30 04 am" src="https://user-images.githubusercontent.com/4056966/52731185-b3b23280-2fef-11e9-8010-b323a912d50b.png">

**Comment by jaharkes** [comment]
For one, this is an issue with the python bindings (https://github.com/openslide/openslide-python) so this bug is filed in the wrong place.

And aside from that, the `deepzoom_tile.py` example script is a command line application that reads a wholeslide image and outputs a deepzoom compatible layout/directory that can be served by a static webserver, i.e. no code has to run to handle actual web requests, it just has to be able to serve static files.

The relevant message in the log you posted was

>  deepzoom_tile.py: error: Missing slide argument

And the comments in the file itself that state

> deepzoom_tile - Convert whole-slide images to Deep Zoom format

> An example program to generate a Deep Zoom directory tree from a slide.

**Comment by ducpm0301** [comment]
Dear,
I am already now, but can you give a example command for run it. Thanks you alot.

**Comment by jaharkes** [comment]
This is still against the wrong repository, and it is not actually a bug, just a usage problem. Maybe it could be filed as a lack of documentation issue in the openslide/openslide-python repository.

I think you can just run 'deepzoom_tile.py <name of slide>' and go from there.
