### ISSUE TITLE
Openslide is not importing in python

### ISSUE THREAD

**Issue by ahsan44411** [openslide/openslide#281]
Kindly help.

I have done pip install openslide-python and download Windows Binary 2016-07-17 version and added bin folder to the path variable but still, I am unable to import openslide in code.

![Untitled](https://user-images.githubusercontent.com/30962013/66215014-96fa6600-e677-11e9-83a2-6672b05d9370.png)

Please tell me what am I doing wrong this has really frustrated me and wasted a lot of my hours

**Comment by bgilbert** [comment]
There's not enough information here to act on.  Since this issue is a couple months old, I'll close.  Please feel free to reopen with more information about what error you're seeing.

**Comment by LiesMH** [comment]
Hi ashan44411, 

It's been months since you posted this but I recently faced the same issue and it took me hours to solve. I hope you have worked it out by now, but I wanted to post my solution here in case more people are facing this and find your post. 

I had succesfully: 
- downloaded openslide windows binary 34
- downloaded openslide-python 1.1.1
- installed openslide-python via the cmd with pip

Then I tried to import openslide but got an error from init.py and lowlevel.py while pulling 'libopenslide-0.dll', because that item could not be found

libopenslide-0.dll is in the openslide windows binary 64 bin path (not in the openslide-python download), but adding that path to environment variables also did not help. 

The solution I found: 
1. open lowlevel.py and go to this line: 
if platform.system() == 'Windows':
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
2. Change it into: 
if platform.system() == 'Windows':
    _lib = cdll.LoadLibrary('C:/Users/..../openslide-win32-20171122/bin/libopenslide-0.dll')
------>(Of course, instead of _'C:/Users/.../openslide-win32-20171122/bin/libopenslide-0.dll'_ use the path where libopenlside-0.dll is located on your computer)
3. Save lowlevel.py
4. Try to import openslide again 

For me this was effective! All other options (re-installing openslide, adding to PATH, installing py-wsi instead) were not.
