### ISSUE TITLE
Re-adding cmake support: now an option?

### ISSUE THREAD

**Issue by emmenlau** [openslide/openslide#315]
## Context

**Issue type**: feature request
**Operating system**: all
**Platform**: all
**OpenSlide version**: master

## Details

I know that cmake support was dropped in 2013. The reason was that the maintenance overhead was not worth the additional benefits. Now its 2020, and I was curious if this can be revisited?

In the C/C++ world, many things have changed. On Windows, its now quite easy to compile software with the clang front end for Visual Studio that is included even in the free versions. And cmake can be considered basically a standard. It makes build instructions a lot more readable, and is very well maintained. OpenJPEG for example has native cmake support.

**Comment by bgilbert** [comment]
The maintenance overhead was due to the fact that we had to maintain multiple build systems in parallel.  I don't think we should start doing that again.  Even if OpenSlide itself could be built with CMake, OpenSlide requires many other libraries from the Linux ecosystem, and many of those do not support CMake.  So it wouldn't get you much closer to producing a working Windows build without additional tools.  And it doesn't seem particularly necessary, since we already have [openslide-winbuild](https://github.com/openslide/openslide-winbuild/) for building OpenSlide on Windows.  (Though, yes, it's broken right now.)

I'd also tend to disagree that CMake is readable.  :slightly_smiling_face:  The Linux community seems to be moving toward Meson; if anything, we should probably think about doing the same.

**Comment by emmenlau** [comment]
I agree that many of the dependencies are using meson! And meson is really nice, no objections. If OpenSlide could support meson that would be great too. I just don't speak any meson myself so I could not help with this.

I did not mean to say that cmake is perfect. But its just omni-present in open source projects nowadays so you can find quick and easy support. They also get your PRs merged quickly, and the support is okay (typical fix times ~2months, typical release cycles ~3 months).

My main incentive would be to have a better Windows build. I used to be a huge fan of mingw, and I helped move MSYS2 forward for the better part of a year. Both projects have great ideals but deeply suffer from lack of manpower. I certainly do not want to object, if you see this as the best route forward. But after spending significant time with these projects I've learned the hard way that builds are more often broken than not, and there was zero support. I'm far from a fan of Microsoft, but the build experience with clang-cl and the Visual Studio command line tools in a Cygwin bash shell is actually pretty close to developing on Linux. And clang produces on average 5-15% faster code on MSVC (my personal experience, no benchmarks, so take it with two grains of salt).

Thats really just my two cents, please close the issue if you find it not relevant. And thanks for your consideration.

**Comment by bgilbert** [comment]
Thanks for the feedback.  To be clear, openslide-winbuild running on Windows uses MinGW-w64 inside Cygwin; I originally tried MinGW with MSYS but I agree that it seemed under-resourced.  The official Windows binaries are cross-built on Linux, and I expect that would continue to be the case, since it reduces the amount of development tooling needed.  It'd be nice if we could get other development environments working, but I'm hesitant about putting in a lot of work to support them, because we're also quite resource-constrained.  :slightly_smiling_face: 

FWIW, my experience with openslide-winbuild is that Windows-specific build breakage is primarily due to source code changes in upstream projects rather than to the build system _per se_.  That problem has seemed to reduce over time, as cross-platform CI has become more of the norm in open-source projects.  And in my experience, projects are usually pretty responsive to patches that fix their builds on Windows.

I've filed #316 to consider a switch to Meson, and I'll close out this issue.  Thanks again for bringing this up, though; I appreciate it.

**Comment by bgilbert** [comment]
The Git `main` branch has now been switched to Meson.
