### ISSUE TITLE
Unable to install on Ubuntu in Docker environment

### ISSUE THREAD

**Issue by kuri54** [openslide/openslide#340]
## Context
**Operating system** : Ubuntu18.04 running on docker
**Platform** : 64-bit x86 
**OpenSlide version**: Latest

## Details
When I try to install openslide-python, I get

> 1. install OpenSlide
> 2. pip install openslide-python

I did so because of the above instructions.

Steps
1. create `openslide `folder
2. ` cd openslide`
3. `wget https://github.com/openslide/openslide/releases/download/v3.4.1/openslide-3.4.1.tar.gz`
4. `tar -xvf openslide-3.4.1.tar.gz`
5. `cd openslide-3.4.1`
6. `./configure`

## Error message
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/work/openslide-python/openslide-3.4.1':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
```

I get an error at step 6.
Am I doing something wrong?

Can you please tell me the correct installation procedure?

I have also tried the following
**Install with apt-get**
1. `sudo apt-get install openslide-tools`
2. `sudo apt-get install python-openslide`
I could not import openslide with this procedure.

**Install from Local environment with brew**
```
==> Checking for dependents of upgraded formulae...
==> No broken dependents found!
```

I'm very sorry to be so persistent. 
Can you please tell me the correct installation procedure in detail?

**Comment by bgilbert** [comment]
> `configure: error: no acceptable C compiler found in $PATH`

As it says, if you're building from source, you need a C compiler.  You'll also need the development headers for the libraries listed in the README.

However, if you're using an Ubuntu 18.04 system, I'd recommend installing with `apt-get` instead.  I assume you meant `python-openslide` instead of `python-openslide-tools` (and `sudo` instead of `sodo`)?  If so, what happened when you tried to `import openslide`?

> Can you please tell me the correct installation procedure in detail?

Support questions are out of scope for this bug tracker.  You could try the openslide-users mailing list.

**Comment by kuri54** [comment]
Thanks for the reply.

First, I fixed the typo.
Sorry about that.

>  I assume you meant python-openslide instead of python-openslide-tools (and sudo instead of sodo)?

Yes. That's right.
It was a typo and I fixed it.

> If so, what happened when you tried to import openslide?

The `sudo apt-get install openslide-tools` worked, but the `sudo apt-get install python-openslide` gave me an error that I think was `gcc` related.
(I apologize for not being able to paste the detailed error message. I will be able to paste them tomorrow when I go to work.)

**Comment by Monk5088** [comment]
ERROR: Command errored out with exit status 1: /home/nagarajudasari/rajugpu/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n1u37_c5/openslide-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n1u37_c5/openslide-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-untcgkks/install-record.txt --single-version-externally-managed --compile --install-headers /home/nagarajudasari/rajugpu/include/site/python3.8/openslide-python Check the logs for full command output.

in mine, it shows this error when I try to do the same steps.
And the open-slide is not getting installed because of this error.
Can anyone help me, please?

**Comment by szrobi96** [comment]
This resolved my problem:
```
sudo apt install build-essential
```
