### ISSUE TITLE
Is there a way to clean up error or put osr object back into normal state?

### ISSUE THREAD

**Issue by kylajung** [openslide/openslide#347]
## Context

**Issue type** : Question
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Mac OS Big Sur (11.4)
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64bit ARM (M1)
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
Hi! I am trying to write an openslide-wrapping library for node.js.
According to the [C API documentation](https://openslide.org/api/openslide_8h.html), it is recommended to check the error after each call :
> If writing wrappers for OpenSlide in languages that support exceptions, it is recommended that the error state be checked after each call and converted into an exception for that language.

But after putting an error check after each call, I noticed that I cannot recover from error state.
```c
openslide_t *osr = openslide_open("/path/to/slide");
openslide_read_region(osr, buf1, 0, 0, 0, -100, -100); // this puts osr into error state
openslide_get_error(osr); // returns an error
openslide_read_region(osr, buf2, 0, 0, 0, 100, 100); // this also fails
openslide_get_error(osr); // returns error from first openslide_read_region call
```
So the first openslide_read_region seems to put the `osr` object into an error state.
The `negative width or height` is a very simple error, and it would be nice if the proceeding calls act normally if the caller uses proper parameters.
I have read the C API doc and I couldn't find a way to put `osr` back to normal state.

What I am trying to do is as something like this:
```javascript
const wsi = new OpenSlide("/path/to/slide");
try {
    wsi.readRegion(0, 0, 0, -300, -300); // This will fail
} catch (err) {
    wsi.readRegion(0, 0, 0, 300, 300); // try again with normal parameters
}
```

Any suggestions?

**Comment by bgilbert** [comment]
Once the slide object enters an error state, the only option is to close it and reopen the slide.  This allows the caller to perform multiple graphics operations sequentially, and then check errors once at the end.

Negative widths/heights are indeed an unusual case because OpenSlide could choose to allow recovery from them.  For consistency, though, we handle them the same way.

Depending how your binding is structured, it'll need to do its own width/height checks anyway before allocating a buffer, or else it could try to allocate e.g. `-100 * 100 * 4` = -40000 bytes for the pixel data.  That gives you an opportunity to raise your own error before calling into OpenSlide, which is [what OpenSlide Python does](https://github.com/openslide/openslide-python/blob/fc14e86577a6f1be3d6b1118d839f1e2d70a0197/openslide/lowlevel.py#L226-L238).
