### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [openslide/openslide#351]
https://github.com/openslide/openslide/compare/v3.4.1...main shows +120 commits since last release which was +7 years ago.
I think that it would be good to flush current change and make new release 😃

**Comment by bgilbert** [comment]
Yup, it'll happen.  There are a few things to clean up first, though, so it won't happen immediately.

**Comment by bgilbert** [comment]
In particular, we should probably get Windows builds working again.

**Comment by hhoeflin** [comment]
openslide-python references an openslide 3.5.0 release ... is that out yet? Last release on github still points to 3.4.1. Thanks!

**Comment by bgilbert** [comment]
Nope, it's not.  There's some new API in Git main which will eventually be released as 3.5.0, but the release is not yet imminent.

**Comment by kwiechen** [comment]
is it possible to include the vmic driver?

**Comment by bgilbert** [comment]
I'm still finishing up getting CI into shape so we can accept contributions.  Once that's done, I'll ping the open PRs to see whether the authors are willing to update them for review and possible merging.

**Comment by ckcollab** [comment]
Would love this as well, struggling to get caching to work (which requires OpenSlide > 3.5.0) -- thanks for any help!

**Comment by bgilbert** [comment]
Until then, you should be able to build and install from Git for cache configuration support.

**Comment by ckcollab** [comment]
@bgilbert for sure, and of course the fix was simple. I basically needed to remove my old OpenSlide 3.4.1 install by manually deleting the `*.so` files and setting this env var after building OpenSlide `LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"`

Anyway, I ended up having to scrap that server and just made this into a Dockerfile.. hope this helps someone! Expects a `requirements.txt` next to this with your other modules.

```Dockerfile
FROM python:3.11

# Build and install OpenSlide 3.5 .. last release was 2015! Very recent code pushed
# to github, but not released officially..
RUN apt-get update && \
    apt-get install -y autoconf pkg-config libtool libjpeg-dev libpng-dev libopenjp2-7-dev libtiff-dev libglib2.0-dev libcairo2-dev libgtk2.0-dev libxml2-dev libsqlite3-dev

RUN cd /tmp && \
    git clone https://github.com/openslide/openslide.git && \
    cd /tmp/openslide && \
    git checkout dd3a152250b460860614a3a793309245eebbcb7c && \
    autoreconf -i && \
    ./configure && \
    make && \
    make install && \
    rm -rf /tmp/openslide

ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

# Install our normal deps
ADD requirements.txt /requirements.txt

WORKDIR /app

RUN pip install -r /requirements.txt
```

**Comment by mhwilder** [comment]
Is there any update on putting out a new release? Specifically, I'm trying to access some of the new functionality (like DICOM loading) but as far as I can tell the version installed on my Mac with brew is 3.4.1 from 2015. I'm also confused because I'm interacting with openslide through the Python API which mentions OpenSlide versions 3.5.0 and 4.0.0 which I can't find reference to in this repo. Any estimate on when the new release will come out? Thanks!

**Comment by bgilbert** [comment]
We're waiting on libdicom 1.0, which is expected later this month after some API concerns are addressed.  I expect OpenSlide 4.0.0 to come out in early September.

We're calling the upcoming release version 4.0.0 because of the breaking changes in #413 and #472 (which shouldn't affect many people in practice).  The OpenSlide Python release notes refer to 3.5.0 because that was the original name of the release.

Thanks for your patience.  I know this has been a very long time coming.

**Comment by cowrturn** [comment]
Looking forward to it.

**Comment by bgilbert** [comment]
[OpenSlide 4.0.0](https://github.com/openslide/openslide/releases/tag/v4.0.0) has been released!

**Comment by ckcollab** [comment]
Wow! Thank you!!!
