### ISSUE TITLE
Outdated config.guess Files

### ISSUE THREAD

**Issue by yining765** [openslide/openslide#374]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Arch Linux 5.18.7-arch1-1
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64 bit RISC-V
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
When I was building the package for the `riscv64` platform, the `./configure` step reported `./config.guess: unable to guess system type`. When I updated the relevant files with `autoreconf -fi`, the build was successful. So `config.guess` and `config.sub` in this project need to be updated to work with more architectures.

**Comment by bgilbert** [comment]
OpenSlide 3.4.1 was released in 2015, so this makes sense.

We don't commit `config.guess`/`config.sub` to Git, so this will be fixed automatically as part of the next release, which I'm hoping will happen in the upcoming months.  Since there's nothing additional to do here, I'll go ahead and close this out.  Thanks for reporting!
