### ISSUE TITLE
WebP Compression is not Configured

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#416]
## Context

**Issue type** feature request
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): TIF

## Details
I can generate pyramid TIF and BIGTIFF files with libvips. When using jpeg compression, I can then open them with openslide.
But when using WebP Compression instead, openslide cannot open the generated tifs anymore.

The error is:

WEBP compression support is not configured.
openslide-show-properties.exe: exampleWebP.tif: Unsupported TIFF compression: 50001

What would we need to do to support WebP Compression? (libvips supports that already).

Thanks!

**Comment by bgilbert** [comment]
It looks like you're using the Windows binaries?  We don't compile libtiff with WebP support because I'm not aware of any scanners that create WebP-encoded images.  Are these files that you're generating yourself, or are you getting them from a particular scanner?

**Comment by jetic83** [comment]
They would he generated by ourselves.

**Comment by jetic83** [comment]
It would be a generic TIFF, that openslide already supports if created with JPEG. It would be a pyramid image generated with libvips. Only the compression would be webp.

**Comment by bgilbert** [comment]
In order to keep the scope of OpenSlide manageable, we don't attempt to support every possible pyramidal image, only those created by slide scanners.  I'm therefore going to close this as out of scope.  If there's a slide scanner that produces WebP output, we can revisit this.

If you want to use OpenSlide to read WebP-compressed TIFF files on Windows, you could create your own build by adding libwebp to openslide-winbuild and linking libtiff with it.
