### ISSUE TITLE
Black tiles

### ISSUE THREAD

**Issue by ginalster** [openslide/openslide#443]
### Operating system

Windows 2010

### Platform

x64

### OpenSlide version

3.4.0

### Slide format

MRXS

### Issue details

I am using OpenSlideNet but which is using openslide to retrieve the tiles. I am getting black portions on tiles, where I assume there is no data (MRXS optimization?).  This does not occur using vips. Is there any options to set the background?

-Gina

![0_0](https://user-images.githubusercontent.com/131937300/235413466-290fabb8-9e88-4ab9-820b-aed223971bb1.jpg)

**Comment by bgilbert** [comment]
Correct, there is no data there.  Some slides don't include pixel data in every possible location.  OpenSlide isn't producing black pixels, though; it's producing transparent ones.  You can use the alpha component of the pixel data to locate these pixels.

You're seeing black pixels because OpenSlide uses premultiplied alpha, so when the alpha component of a pixel is 0, the R/G/B components are also 0.  See [this page](https://openslide.org/docs/premultiplied-argb/) for more info.
