### ISSUE TITLE
`STATUS_STACK_BUFFER_OVERRUN` reading invalid JPEG tile

### ISSUE THREAD

**Issue by ayamany224** [openslide/openslide#564]
### Operating system

windows server

### Platform

64

### OpenSlide version

latest

### Slide format

.tif

### Issue details

Hi, I'm having a strange issue i got a tif slide from kfbio scanner but something wrong happened while scanning so when technician added slide to my web site then my code started to tile it tif file is opened normaly but i got this warning TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.

then after some seconds it crashes and my service stops any thougths to handle this before start tiling

**Comment by bgilbert** [comment]
Please give the actual Windows and OpenSlide versions you're using, not `server` and `latest`.  Are you using an [official binary build](https://openslide.org/download/#binaries)?  If so, what's its datecode?

OpenSlide doesn't have special code to support KFBIO scans, so the slide is being read as a generic tiled TIFF.  If OpenSlide normally works for other KFBIO scans, it's possible that your slide file is damaged.  Otherwise, it's possible that KFBIO writes partially invalid TIFF files, and so OpenSlide would need to add special support for that format.

In either case, OpenSlide shouldn't crash.  Can you [upload your slide file](https://openslide.org/submit/) for analysis?

**Comment by ayamany224** [comment]
actual Operating system: Windows Server 2022 Standard
openslide-win64-20171122

slide link https://drive.google.com/file/d/1StfKxut5ujlYW6oefZHqJkdiw6G4YWLS/view?usp=sharing
im using openside official binary when im tiling my worker service crash while tiling

**Comment by bgilbert** [comment]
Thanks for the information.  openslide-win64-20171122 is not "latest".  It has a nine-year-old version of OpenSlide (3.4.1) and six-year-old versions of OpenSlide's dependencies.  Newer versions of libtiff may have fixed the crash.  Please try again with the 2023-10-11 build and report whether the crash still happens.

Does OpenSlide work correctly for other KFBIO scans?

**Comment by ayamany224** [comment]
this is a sample of error i found inside event viewer Faulting application name: HistoWorkerService.exe, version: 1.0.0.0, time stamp: 0x63747414
Faulting module name: ucrtbase.dll, version: 10.0.22621.2506, time stamp: 0x097c794c
Exception code: 0xc0000409
Fault offset: 0x00000000000525b8
Faulting process id: 0x0x5D10
Faulting application start time: 0x0x1DA6338510C61CD
Faulting application path: D:\Projects\HistoMainWS\HistoWorkerService\HistoWorkerService\bin\Debug\netcoreapp3.1\HistoWorkerService.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 48f08748-9c74-4d3f-87e2-7f8ec50c6201
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bgilbert** [comment]
Okay, thanks.  I'll take a look.

**Comment by ayamany224** [comment]
thank you in advance

**Comment by ayamany224** [comment]
@bgilbert any updates dear?

**Comment by bgilbert** [comment]
FYI, in the open-source software community, pings should be used carefully.  For example, if someone was actively working on an issue and then it stalls for some weeks or months, pinging may be reasonable.  But if no one was actively working on it, or if the issue hasn't been dormant very long, pings can come across as impolite.  There is no contractual response time in open-source software, and developers often have other responsibilities.  If you urgently need a fix, you always have the option of working on the issue yourself and posting your findings.

**Comment by bgilbert** [comment]
I've looked over your slide.  The TIFF metadata has various bugs, as already discussed, but that shouldn't affect the result.  There appear to be many JPEG tiles that were not written to the file, causing JPEG decoding to fail, but OpenSlide can handle that.  The most likely explanation is that libjpeg's error handling, which uses `setjmp`/`longjmp`, is causing the stack to be misaligned or otherwise confusing OS stack protections.  You can test this by setting the `OPENSLIDE_DEBUG` environment variable to `synthetic` and then opening the zero-length filename (`openslide_open("")`) with OpenSlide 4.0.0.  That will cause OpenSlide to run various self-tests, including reading a corrupt JPEG.  If it crashes, the problem is with JPEG error handling and not this specific slide file.

This will probably require some additional debugging on your side.  Is your program a C/C++ program directly linked with OpenSlide, or are you invoking OpenSlide from another language via an FFI?  Are you using any special build flags that might affect handling of the stack?  A backtrace would be helpful, as well as the exception subcode, since exception 0xc0000409 (`STATUS_STACK_BUFFER_OVERRUN`) [can have multiple causes](https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655).

**Comment by bgilbert** [comment]
Another possibility is that your code has a bug, such as a double free, in its `openslide_read_region()` error path.

**Comment by bgilbert** [comment]
The `TIFFReadDirectoryCheckOrder` log messages should be silenced by https://github.com/openslide/openslide/pull/569.

**Comment by ayamany224** [comment]
Hello @bgilbert, I've managed to pinpoint the problem I was encountering. It seems that my tiles were being generated within an asynchronous method without proper await, causing the exception to slip through without being handled in the catch block. After rectifying this by ensuring proper await, everything is now functioning smoothly. Thank you for your assistance!
