### ISSUE TITLE
NDPI: A resolution that does not belong to the file appears

### ISSUE THREAD

**Issue by FiyZou** [openslide/openslide#613]
### Operating system

Ubuntu

### Platform

64-bit

### OpenSlide version

4.0

### Slide format

NDPI

### Issue details

![image](https://github.com/openslide/openslide/assets/26448696/8a589953-1d53-444c-933d-28d37e4f4dc0)
I used CGO to parse, but a resolution that does not belong to the file appears

**Comment by FiyZou** [comment]
I used the command tiffinfo to check and didn't find the resolution outside the red box

**Comment by bgilbert** [comment]
Yes, that's correct.  libjpeg can efficiently downscale JPEGs during decoding, and OpenSlide's readers for Hamamatsu VMS and NDPI use that feature to synthesize extra downsampled levels.  This is especially important for VMS, which only has two pyramid levels otherwise, but is also helpful for NDPI.  OpenSlide always uses native NDPI levels when those exist, and otherwise adds downsamples with factors of 2, 4, and 8 from the NDPI levels.

Are the extra levels causing any problems for you?

**Comment by FiyZou** [comment]
ok,I would like to be able to directly get the number and resolution of the original layers, but for now I am using the smallest layer as the tile unit

**Comment by bgilbert** [comment]
Can you explain why that information would be useful?
